/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Number */

#ifndef _Included_Number
#define _Included_Number
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Number
 * Method:    firstNative
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Number_firstNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     Number
 * Method:    secondNative
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Number_secondNative
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
