/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayMinMax */

#ifndef _Included_ArrayMinMax
#define _Included_ArrayMinMax
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayMinMax
 * Method:    displayResult
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ArrayMinMax_displayResult
  (JNIEnv *, jobject, jint);

/*
 * Class:     ArrayMinMax
 * Method:    displayDifference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ArrayMinMax_displayDifference
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
