/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HonoursClassification */

#ifndef _Included_HonoursClassification
#define _Included_HonoursClassification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HonoursClassification
 * Method:    calculateDiploma
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HonoursClassification_calculateDiploma
  (JNIEnv *, jobject);

/*
 * Class:     HonoursClassification
 * Method:    calculateDegree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HonoursClassification_calculateDegree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
